services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
        DATA_DIR: /data
        ALLOW_DEBUG: "1"          # enables /api/debug/db
        JWT_SECRET: ${JWT_SECRET:-...}
        NEXT_PUBLIC_HOCUSPOCUS_URL: ${NEXT_PUBLIC_HOCUSPOCUS_URL:-wss://ws.project.collab.name.ng}
    volumes:
      - projects-data:/data
    depends_on:
      - collab
    restart: unless-stopped

  collab:
    build:
      context: .
      dockerfile: docker/Dockerfile.collab
    ports:
      - "1235:1235"
    environment:
      - HOCUSPOCUS_PORT=1235
      - DATA_DIR=/data
    volumes:
      - projects-data:/data
    restart: unless-stopped

volumes:
  projects-data: